### ISSUE TITLE
Crash when opening skin customization settings (1.19.3)

### ISSUE THREAD

**Issue by userbyte** [dragonostic/of-capes#6]
I'm aware 1.19.3 isn't officially supported but... the mod works fine for the most part, no major code changes seem necessary to support 1.19.3. The only issue I've noticed is that the game crashes when opening the skin customization settings.

Here's the crash report:
```
---- Minecraft Crash Report ----
// Oops.

Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
	at net.minecraft.class_440.handler$zzb000$iTInject(class_440.java:534)
	at net.minecraft.class_440.method_25426(class_440.java:35)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_429.method_47624(class_429.java:172)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:172)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_7838.method_25402(class_7838.java:155)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:215)
	at net.minecraft.class_310.method_1523(class_310.java:1225)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

Relevant versions: OF Capes 2.0.0, Fabric 0.14.12, Intermediary Mappings 1.19.3, Minecraft 1.19.3

**Comment by SuchBlue** [comment]
Fixed in my pull request for 1.20.1 ([https://github.com/dragonostic/of-capes/pull/8](https://github.com/dragonostic/of-capes/pull/8))
